name: Notifications

on: [push]

jobs:
  tg:
    name: Telegram notification
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.NOTIFICATIONS_TELEGRAM_TO }}
          token: ${{ secrets.NOTIFICATIONS_TELEGRAM_TOKEN }}
          message: 123123
